name: Convert notebook to PDF

on:
  push:
    branches: [main]
    paths:
      - "scripts/*.ipynb"
      - ".github/workflows/convert-notebook.yml"
  workflow_dispatch:

jobs:
  convert-and-commit:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    env:
        DRY_RUN: "false"

    steps:
      - uses: actions/checkout@v6

      - name: Convert notebooks
        uses: amanda-amy-frost/jupyter-to-pdf-action@v1
        with:
          dry_run: ${{ env.DRY_RUN }}
          input_dirs: "scripts"
          output_dir: "."
          execute: "true"
          requirements: "requirements.txt"

      - name: Commit PDF back to repo
        if: ${{ env.DRY_RUN == 'false' }}
        run: |
          git config user.name "Amanda Frost"
          git config user.email "amanda.amy.frost@gmail.com"
          git add **/*.pdf
          git commit -m "Update analysis notebook PDF" ||
            echo "No changes to commit"
          git push
